In [1]:
import numpy as np
import gym
import time
import random
import time
from IPython.display import clear_output
from IPython.display import display

In [2]:
env=gym.make("FrozenLake-v1")

In [3]:

action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
###Parameters that will be twicked for performance #####

num_episodes=10000
max_steps_per_episode=200 # from 100 to 200; the score icnresaed from 70% to 75% 

learning_rate=0.1
discount_rate=0.99 # lowering to 0.5 made it worst

##Episolon Greedy Startegy
exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01  ## Could rather be 0.001 ; Changing from 0.01 to 0.001 improved hardly by 0.5%



In [5]:
rewards_all_episodes=[]  # Save rewards from each episode
step_executed_counter=0
for episode in range(num_episodes):
    state=env.reset()[0] 
    done=False  # to check if episode is completed
    rewards_current_episode =0  # rewards in a current episode
    
    for step in range(max_steps_per_episode):
        step_executed_counter= step_executed_counter+1
        #Exploration- exploitation trade-off to choose an action for given state 
        exploration_rate_threshold=random.uniform(0,1)   # agent will explore or exploit in a given time step
        if exploration_rate_threshold >exploration_rate:
            action=np.argmax(q_table[state,:])  # exploit ; use highest q value for current state
        else:
            action=env.action_space.sample() # explore; use random option
            
        new_state,reward,done,truncated,info=env.step(action)
        
        #Update Q-Table for Q(s,a); Qnew=(1-alpha)q  + alpha (R + gamma *max(q))
                #a= q_table[state, action] *(1 - learning_rate) 
                #b=learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        q_table[state, action] =q_table[state, action] *(1 - learning_rate) +learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state= new_state
        rewards_current_episode +=reward
        
        if done==True:
            break
        
        #Decay exploration rate
    exploration_rate=min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    #print("Episode Number:", episode, "rewards_all_episodes:", np.size(rewards_all_episodes))

In [6]:
#Calacualte and print the average reward per thousand episodes

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)

count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print (count, ": ", str(sum(r/1000)))
    count +=1000

********Average reward per thousand episodes********

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


In [7]:
np.size(rewards_all_episodes)

10000

In [8]:
num_episodes


10000

In [9]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
step_executed_counter

173464

In [11]:
# Create the environment with render mode specified
env = gym.make('CartPole-v1', render_mode="rgb_array")

for episode in range(num_episodes):
    state = env.reset()[0]
    print(state)
    done = False
    print("**************EPISODE: ", episode+1, "***********\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode): 
        clear_output(wait=True)
        env.render() ## Render current state of play to display; 'rgb_array'; 'human'
        
        #display(render_output.outputs)
        
        time.sleep(0.5)
        
        action=np.argmax(q_table[state,:])
        new_state,reward,done,truncated,info=env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render('human') ## 'rgb_array'
            if reward == 1:
                print("******You reached the goal******")
                time.sleep(5)
            else:
                print("******You fell through a hole******")
                time.sleep(5)
            clear_output(wait=True)
            break
            
        state=new_state
        
env.close()
                

IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
name 'render_output' is not defined


In [ ]:
state